"""improve

Revision ID: 38b2c6054338
Revises: e77c8cd7e000
Create Date: 2025-04-19 20:56:06.830166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b2c6054338'
down_revision: Union[str, None] = 'e77c8cd7e000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('business_id', sa.String(length=255), nullable=True))
    op.add_column('chats', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('chats', sa.Column('firstname', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_chat', 'chats', ['chat_id', 'business_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chat', 'chats', type_='unique')
    op.drop_column('chats', 'firstname')
    op.drop_column('chats', 'username')
    op.drop_column('admins', 'business_id')
    # ### end Alembic commands ###
