"""improve

Revision ID: c24fcdf84e07
Revises: 38b2c6054338
Create Date: 2025-04-19 21:09:40.693287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c24fcdf84e07'
down_revision: Union[str, None] = '38b2c6054338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('admin_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
